#!/usr/bin/env bash
# Cross-platform-equivalent first start/update entrypoint for Ubuntu.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"
GENERATED_PASSWORD=""

cd "$ROOT_DIR"

if ! command -v docker >/dev/null 2>&1; then
  echo "ERROR: Docker is not installed or is not available in PATH." >&2
  exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "ERROR: Docker Compose v2 is required (the 'docker compose' command)." >&2
  exit 1
fi

dotenv_value() {
  local key="$1"
  local value
  value="$(awk -v wanted="$key" '
    index($0, wanted "=") == 1 {
      sub(/^[^=]*=/, "")
      sub(/\r$/, "")
      print
      exit
    }
  ' "$ENV_FILE")"
  value="${value%\"}"
  value="${value#\"}"
  printf '%s' "$value"
}

set_dotenv_value() {
  local key="$1"
  local value="$2"
  local temp_file
  temp_file="$(mktemp "${ENV_FILE}.tmp.XXXXXX")"
  awk -v wanted="$key" -v replacement="$value" '
    BEGIN { found = 0 }
    index($0, wanted "=") == 1 {
      print wanted "=" replacement
      found = 1
      next
    }
    { print }
    END {
      if (!found) {
        print wanted "=" replacement
      }
    }
  ' "$ENV_FILE" > "$temp_file"
  mv "$temp_file" "$ENV_FILE"
  chmod 600 "$ENV_FILE"
}

if [[ ! -f "$ENV_FILE" ]]; then
  BASE_URL_VALUE="${SUBSHARE_BASE_URL:-}"
  if [[ -z "$BASE_URL_VALUE" && -t 0 ]]; then
    read -r -p "Public URL [http://localhost]: " BASE_URL_VALUE
  fi
  BASE_URL_VALUE="${BASE_URL_VALUE:-http://localhost}"
  BASE_URL_VALUE="${BASE_URL_VALUE%/}"

  if [[ ! "$BASE_URL_VALUE" =~ ^https?://[^/[:space:]]+(:[0-9]+)?$ ]]; then
    echo "ERROR: public URL must contain only http(s) scheme and host, without a path." >&2
    exit 1
  fi

  ADMIN_USER_VALUE="${SUBSHARE_ADMIN_USER:-admin}"
  if [[ ! "$ADMIN_USER_VALUE" =~ ^[A-Za-z0-9._-]+$ ]]; then
    echo "ERROR: admin username may contain only letters, digits, dot, underscore and hyphen." >&2
    exit 1
  fi

  if [[ -n "${SUBSHARE_ADMIN_PASSWORD:-}" ]]; then
    GENERATED_PASSWORD="$SUBSHARE_ADMIN_PASSWORD"
  else
    GENERATED_PASSWORD="$(od -An -N24 -tx1 /dev/urandom | tr -d ' \n')"
  fi

  {
    printf '# Generated by scripts/start.sh. Keep this file private.\n'
    printf 'ADMIN_USER=%s\n' "$ADMIN_USER_VALUE"
    printf 'ADMIN_PASSWORD=%s\n' "$GENERATED_PASSWORD"
    printf 'BASE_URL=%s\n' "$BASE_URL_VALUE"
    printf 'CORS_ORIGINS=\n'
    printf 'TRUSTED_PROXIES=172.16.0.0/12\n'
    printf 'DB_PATH=/app/data/app.db\n'
    printf 'DB_JOURNAL_MODE=WAL\n'
    printf 'BACKUP_PATH=/app/data/backups/app.db\n'
    printf 'BACKUP_INTERVAL=1h\n'
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  echo "Created $ENV_FILE"
fi

BASE_URL_VALUE="$(dotenv_value BASE_URL)"
ADMIN_PASSWORD_VALUE="$(dotenv_value ADMIN_PASSWORD)"
if [[ -z "$BASE_URL_VALUE" ]]; then
  BASE_URL_VALUE="${SUBSHARE_BASE_URL:-}"
  if [[ -z "$BASE_URL_VALUE" && -t 0 ]]; then
    read -r -p "Public URL [http://localhost]: " BASE_URL_VALUE
  fi
  BASE_URL_VALUE="${BASE_URL_VALUE:-http://localhost}"
  BASE_URL_VALUE="${BASE_URL_VALUE%/}"
  if [[ ! "$BASE_URL_VALUE" =~ ^https?://[^/[:space:]]+(:[0-9]+)?$ ]]; then
    echo "ERROR: public URL must contain only http(s) scheme and host, without a path." >&2
    exit 1
  fi
  set_dotenv_value BASE_URL "$BASE_URL_VALUE"
  echo "Configured BASE_URL in $ENV_FILE"
fi
if [[ -z "$ADMIN_PASSWORD_VALUE" ]]; then
  GENERATED_PASSWORD="${SUBSHARE_ADMIN_PASSWORD:-$(od -An -N24 -tx1 /dev/urandom | tr -d ' \n')}"
  set_dotenv_value ADMIN_PASSWORD "$GENERATED_PASSWORD"
  ADMIN_PASSWORD_VALUE="$GENERATED_PASSWORD"
  echo "Generated ADMIN_PASSWORD in $ENV_FILE"
fi

export BUILD_COMMIT="${BUILD_COMMIT:-$(git rev-parse --short HEAD 2>/dev/null || printf unknown)}"
export BUILD_VERSION="${BUILD_VERSION:-$(git describe --tags --always 2>/dev/null || printf local)}"
export BUILD_TIME="${BUILD_TIME:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}"

docker compose config --quiet

if [[ -f "$ROOT_DIR/data/app.db" ]]; then
  echo "Checking whether legacy data/app.db needs to be imported..."
  docker compose stop backend >/dev/null 2>&1 || true
  docker compose --profile tools run --rm migrate-legacy-data
fi

echo "Building and starting SubShare..."
if ! docker compose up -d --build --remove-orphans --wait --wait-timeout 180; then
  docker compose logs --tail=120
  exit 1
fi

echo
echo "SubShare is ready: ${BASE_URL_VALUE}/admin/login"
if [[ -n "$GENERATED_PASSWORD" ]]; then
  echo "Admin user: ${SUBSHARE_ADMIN_USER:-admin}"
  echo "Generated admin password: $GENERATED_PASSWORD"
  echo "Save this password now; it is stored only in the local .env file."
fi
echo "Logs: docker compose logs -f"
echo "Stop: docker compose down"
