param(
    [string]$BaseUrl = "",
    [string]$AdminUser = "admin",
    [string]$AdminPassword = ""
)

$ErrorActionPreference = "Stop"
$rootDir = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $rootDir ".env"
$generatedPassword = ""

Set-Location $rootDir

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    throw "Docker is not installed or is not available in PATH."
}
& docker compose version *> $null
if ($LASTEXITCODE -ne 0) {
    throw "Docker Compose v2 is required (the 'docker compose' command)."
}

function Get-DotEnvValue {
    param([string]$Key)

    $line = Get-Content -LiteralPath $envFile |
        Where-Object { $_.StartsWith("$Key=", [System.StringComparison]::Ordinal) } |
        Select-Object -First 1
    if ($null -eq $line) {
        return ""
    }
    return $line.Substring($Key.Length + 1).Trim().Trim('"')
}

function Get-DotEnvExactValue {
    param([string]$Key)

    $line = Get-Content -LiteralPath $envFile |
        Where-Object { $_.StartsWith("$Key=", [System.StringComparison]::Ordinal) } |
        Select-Object -First 1
    if ($null -eq $line) {
        return ""
    }
    $value = $line.Substring($Key.Length + 1)
    if ($value.Length -ge 2 -and $value[0] -eq '"' -and $value[$value.Length - 1] -eq '"') {
        return $value.Substring(1, $value.Length - 2)
    }
    return $value
}

function ConvertTo-DotEnvQuotedValue {
    param([string]$Value)

    $escaped = $Value.Replace('\', '\\').Replace('"', '\"').Replace('$', '$$').Replace("`r", '\r').Replace("`n", '\n')
    return '"' + $escaped + '"'
}

function Set-DotEnvValue {
    param(
        [string]$Key,
        [string]$Value
    )

    $lines = [System.Collections.Generic.List[string]]::new()
    if (Test-Path -LiteralPath $envFile) {
        Get-Content -LiteralPath $envFile | ForEach-Object { $lines.Add($_) }
    }
    $found = $false
    for ($index = 0; $index -lt $lines.Count; $index++) {
        if ($lines[$index].StartsWith("$Key=", [System.StringComparison]::Ordinal)) {
            $lines[$index] = "$Key=$Value"
            $found = $true
            break
        }
    }
    if (-not $found) {
        $lines.Add("$Key=$Value")
    }
    $contents = ($lines -join "`n") + "`n"
    [System.IO.File]::WriteAllText($envFile, $contents, [System.Text.UTF8Encoding]::new($false))
}

if (-not (Test-Path -LiteralPath $envFile)) {
    if ([string]::IsNullOrWhiteSpace($BaseUrl)) {
        if (-not [string]::IsNullOrWhiteSpace($env:SUBSHARE_BASE_URL)) {
            $BaseUrl = $env:SUBSHARE_BASE_URL
        } else {
            $enteredUrl = Read-Host "Public URL [http://localhost]"
            $BaseUrl = if ([string]::IsNullOrWhiteSpace($enteredUrl)) { "http://localhost" } else { $enteredUrl }
        }
    }
    $BaseUrl = $BaseUrl.TrimEnd("/")
    if ($BaseUrl -notmatch '^https?://[^/\s]+(:[0-9]+)?$') {
        throw "Public URL must contain only http(s) scheme and host, without a path."
    }

    if (-not [string]::IsNullOrWhiteSpace($env:SUBSHARE_ADMIN_USER) -and $AdminUser -eq "admin") {
        $AdminUser = $env:SUBSHARE_ADMIN_USER
    }
    if ($AdminUser -notmatch '^[A-Za-z0-9._-]+$') {
        throw "Admin username may contain only letters, digits, dot, underscore and hyphen."
    }

    if ([string]::IsNullOrEmpty($AdminPassword)) {
        if (-not [string]::IsNullOrEmpty($env:SUBSHARE_ADMIN_PASSWORD)) {
            $AdminPassword = $env:SUBSHARE_ADMIN_PASSWORD
        } else {
            $bytes = New-Object byte[] 24
            $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
            try {
                $rng.GetBytes($bytes)
            } finally {
                $rng.Dispose()
            }
            $AdminPassword = -join ($bytes | ForEach-Object { $_.ToString("x2") })
        }
    }
    $generatedPassword = $AdminPassword

    $contents = @(
        "# Generated by scripts/start.ps1. Keep this file private."
        "ADMIN_USER=$AdminUser"
        "ADMIN_PASSWORD=$(ConvertTo-DotEnvQuotedValue $AdminPassword)"
        "BASE_URL=$BaseUrl"
        "CORS_ORIGINS="
        "TRUSTED_PROXIES=172.16.0.0/12"
        "DB_PATH=/app/data/app.db"
        "DB_JOURNAL_MODE=WAL"
        "BACKUP_PATH=/app/data/backups/app.db"
        "BACKUP_INTERVAL=1h"
        ""
    ) -join "`n"
    [System.IO.File]::WriteAllText($envFile, $contents, [System.Text.UTF8Encoding]::new($false))
    Write-Host "Created $envFile"
}

$resolvedBaseUrl = Get-DotEnvValue "BASE_URL"
$resolvedAdminPassword = Get-DotEnvExactValue "ADMIN_PASSWORD"
if ([string]::IsNullOrWhiteSpace($resolvedBaseUrl)) {
    if ([string]::IsNullOrWhiteSpace($BaseUrl)) {
        if (-not [string]::IsNullOrWhiteSpace($env:SUBSHARE_BASE_URL)) {
            $BaseUrl = $env:SUBSHARE_BASE_URL
        } else {
            $enteredUrl = Read-Host "Public URL [http://localhost]"
            $BaseUrl = if ([string]::IsNullOrWhiteSpace($enteredUrl)) { "http://localhost" } else { $enteredUrl }
        }
    }
    $resolvedBaseUrl = $BaseUrl.TrimEnd("/")
    if ($resolvedBaseUrl -notmatch '^https?://[^/\s]+(:[0-9]+)?$') {
        throw "Public URL must contain only http(s) scheme and host, without a path."
    }
    Set-DotEnvValue "BASE_URL" $resolvedBaseUrl
    Write-Host "Configured BASE_URL in $envFile"
}
if ([string]::IsNullOrEmpty($resolvedAdminPassword)) {
    if ([string]::IsNullOrEmpty($AdminPassword)) {
        if (-not [string]::IsNullOrEmpty($env:SUBSHARE_ADMIN_PASSWORD)) {
            $AdminPassword = $env:SUBSHARE_ADMIN_PASSWORD
        } else {
            $bytes = New-Object byte[] 24
            $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
            try {
                $rng.GetBytes($bytes)
            } finally {
                $rng.Dispose()
            }
            $AdminPassword = -join ($bytes | ForEach-Object { $_.ToString("x2") })
        }
    }
    $generatedPassword = $AdminPassword
    $resolvedAdminPassword = $AdminPassword
    Set-DotEnvValue "ADMIN_PASSWORD" (ConvertTo-DotEnvQuotedValue $resolvedAdminPassword)
    Write-Host "Generated ADMIN_PASSWORD in $envFile"
}

if ([string]::IsNullOrWhiteSpace($env:BUILD_COMMIT)) {
    $env:BUILD_COMMIT = (& git rev-parse --short HEAD 2>$null)
    if ($LASTEXITCODE -ne 0) { $env:BUILD_COMMIT = "unknown" }
}
if ([string]::IsNullOrWhiteSpace($env:BUILD_VERSION)) {
    $env:BUILD_VERSION = (& git describe --tags --always 2>$null)
    if ($LASTEXITCODE -ne 0) { $env:BUILD_VERSION = "local" }
}
if ([string]::IsNullOrWhiteSpace($env:BUILD_TIME)) {
    $env:BUILD_TIME = [DateTime]::UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ")
}

& docker compose config --quiet
if ($LASTEXITCODE -ne 0) { throw "docker compose config validation failed." }

$legacyDatabase = Join-Path $rootDir "data\app.db"
if (Test-Path -LiteralPath $legacyDatabase) {
    Write-Host "Checking whether legacy data/app.db needs to be imported..."
    & docker compose stop backend *> $null
    & docker compose --profile tools run --rm migrate-legacy-data
    if ($LASTEXITCODE -ne 0) { throw "Legacy database import failed." }
}

Write-Host "Building and starting SubShare..."
& docker compose up -d --build --remove-orphans --wait --wait-timeout 180
if ($LASTEXITCODE -ne 0) {
    & docker compose logs --tail=120
    throw "SubShare failed to start."
}

Write-Host ""
Write-Host "SubShare is ready: $resolvedBaseUrl/admin/login"
if (-not [string]::IsNullOrEmpty($generatedPassword)) {
    Write-Host "Admin user: $AdminUser"
    Write-Host "The generated password is stored in the private $envFile file and is not printed."
}
Write-Host "Logs: docker compose logs -f"
Write-Host "Stop: docker compose down"
